#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update -y
sudo apt-get install -y nginx
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sed -i 's/\(listen \)[0-9]\+\(.*\)/\180\2/' /etc/nginx/sites-available/default
sudo echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx restart
